"""handheld reported revisions

Revision ID: 41bd3d7b7998
Revises: 90ab4443243d
Create Date: 2026-08-30 16:44:49.534671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41bd3d7b7998'
down_revision: Union[str, Sequence[str], None] = '90ab4443243d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('handhelds', sa.Column('last_config_revision', sa.Integer(), nullable=True))
    op.add_column('handhelds', sa.Column('last_data_revision', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('handhelds', 'last_data_revision')
    op.drop_column('handhelds', 'last_config_revision')
    # ### end Alembic commands ###
