"""initial schema

Revision ID: 5e0a76389d5b
Revises: 
Create Date: 2026-08-29 19:46:21.395293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e0a76389d5b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('handhelds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('firmware_version', sa.String(length=40), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_ip', sa.String(length=45), nullable=True),
    sa.Column('battery_pct', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_classes_show_id'), 'car_classes', ['show_id'], unique=False)
    op.create_table('judging_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('max_points', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_judging_criteria_show_id'), 'judging_criteria', ['show_id'], unique=False)
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('registration_number', sa.String(length=40), nullable=False),
    sa.Column('display_car_number', sa.String(length=40), nullable=False),
    sa.Column('make', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('owner_name', sa.String(length=120), nullable=True),
    sa.Column('announcer_name', sa.String(length=200), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('UNJUDGED', 'JUDGED', 'FLAGGED_CONFLICT', name='carstatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['car_classes.id'], ),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cars_class_id'), 'cars', ['class_id'], unique=False)
    op.create_index(op.f('ix_cars_registration_number'), 'cars', ['registration_number'], unique=True)
    op.create_index(op.f('ix_cars_show_id'), 'cars', ['show_id'], unique=False)
    op.create_table('judging_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('handheld_id', sa.Integer(), nullable=False),
    sa.Column('judge_name', sa.String(length=120), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'FLAGGED_DUPLICATE', 'REJECTED', name='submissionstatus', native_enum=False, length=32), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['handheld_id'], ['handhelds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_judging_submissions_car_id'), 'judging_submissions', ['car_id'], unique=False)
    op.create_index(op.f('ix_judging_submissions_handheld_id'), 'judging_submissions', ['handheld_id'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('photo_type', sa.Enum('CAR', 'JUDGE_SHEET', name='phototype', native_enum=False, length=32), nullable=False),
    sa.Column('source_handheld_id', sa.Integer(), nullable=True),
    sa.Column('transfer_method', sa.Enum('USB', 'WIFI', name='transfermethod', native_enum=False, length=16), nullable=False),
    sa.Column('transferred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['source_handheld_id'], ['handhelds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_car_id'), 'photos', ['car_id'], unique=False)
    op.create_index(op.f('ix_photos_source_handheld_id'), 'photos', ['source_handheld_id'], unique=False)
    op.create_table('judging_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('criteria_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['criteria_id'], ['judging_criteria.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['judging_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_judging_scores_criteria_id'), 'judging_scores', ['criteria_id'], unique=False)
    op.create_index(op.f('ix_judging_scores_submission_id'), 'judging_scores', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_judging_scores_submission_id'), table_name='judging_scores')
    op.drop_index(op.f('ix_judging_scores_criteria_id'), table_name='judging_scores')
    op.drop_table('judging_scores')
    op.drop_index(op.f('ix_photos_source_handheld_id'), table_name='photos')
    op.drop_index(op.f('ix_photos_car_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_judging_submissions_handheld_id'), table_name='judging_submissions')
    op.drop_index(op.f('ix_judging_submissions_car_id'), table_name='judging_submissions')
    op.drop_table('judging_submissions')
    op.drop_index(op.f('ix_cars_show_id'), table_name='cars')
    op.drop_index(op.f('ix_cars_registration_number'), table_name='cars')
    op.drop_index(op.f('ix_cars_class_id'), table_name='cars')
    op.drop_table('cars')
    op.drop_index(op.f('ix_judging_criteria_show_id'), table_name='judging_criteria')
    op.drop_table('judging_criteria')
    op.drop_index(op.f('ix_car_classes_show_id'), table_name='car_classes')
    op.drop_table('car_classes')
    op.drop_table('shows')
    op.drop_table('handhelds')
    # ### end Alembic commands ###
