"""judging category built-in key

Revision ID: 74239f009b3e
Revises: 7f25ecd68f1a
Create Date: 2026-08-30 17:48:02.201965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74239f009b3e'
down_revision: Union[str, Sequence[str], None] = '7f25ecd68f1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('judging_categories', sa.Column('built_in_key', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('judging_categories', 'built_in_key')
    # ### end Alembic commands ###
