"""initial schema

Revision ID: 8ad4e96210aa
Revises: 
Create Date: 2026-08-30 10:20:33.236679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ad4e96210aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('handhelds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('firmware_version', sa.String(length=40), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_ip', sa.String(length=45), nullable=True),
    sa.Column('battery_pct', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('score_range_max', sa.Integer(), nullable=False),
    sa.Column('overall_impression_enabled', sa.Boolean(), nullable=False),
    sa.Column('top_awards_count', sa.Integer(), nullable=True),
    sa.Column('configuration_revision', sa.Integer(), nullable=False),
    sa.Column('show_data_revision', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle_makes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('source', sa.Enum('SEED', 'LEARNED', name='vehiclesource', native_enum=False, length=16), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active_show_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['active_show_id'], ['shows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('entry_number', sa.String(length=10), nullable=False),
    sa.Column('participant', sa.String(length=120), nullable=True),
    sa.Column('year', sa.String(length=10), nullable=True),
    sa.Column('make', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('vehicle_type', sa.String(length=40), nullable=True),
    sa.Column('make_manually_entered', sa.Boolean(), nullable=False),
    sa.Column('model_manually_entered', sa.Boolean(), nullable=False),
    sa.Column('announcer_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('UNJUDGED', 'JUDGED', 'FLAGGED_CONFLICT', name='carstatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_revision_at_change', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('show_id', 'entry_number', name='uq_car_show_entry_number')
    )
    op.create_index(op.f('ix_cars_entry_number'), 'cars', ['entry_number'], unique=False)
    op.create_index(op.f('ix_cars_show_id'), 'cars', ['show_id'], unique=False)
    op.create_table('judging_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_judging_categories_show_id'), 'judging_categories', ['show_id'], unique=False)
    op.create_table('vehicle_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('source', sa.Enum('SEED', 'LEARNED', name='vehiclesource', native_enum=False, length=16), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['make_id'], ['vehicle_makes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('make_id', 'name', name='uq_vehicle_model_make_name')
    )
    op.create_index(op.f('ix_vehicle_models_make_id'), 'vehicle_models', ['make_id'], unique=False)
    op.create_table('awards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('judge_chosen', sa.Boolean(), nullable=False),
    sa.Column('ranking_basis', sa.Enum('TOTAL', 'ENGINE', 'EXTERIOR', 'INTERIOR', 'PAINT', 'WHEELS_TIRES', name='awardrankingbasis', native_enum=False, length=16), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('winner_car_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ),
    sa.ForeignKeyConstraint(['winner_car_id'], ['cars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_awards_show_id'), 'awards', ['show_id'], unique=False)
    op.create_table('judging_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('entry_number', sa.String(length=10), nullable=False),
    sa.Column('handheld_id', sa.Integer(), nullable=False),
    sa.Column('judge_name', sa.String(length=120), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at_uptime_ms', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('ACCEPTED', 'FLAGGED_DUPLICATE', 'REJECTED', name='submissionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('overall_impression_original_points', sa.Integer(), nullable=True),
    sa.Column('overall_impression_original_range_max', sa.Integer(), nullable=True),
    sa.Column('overall_impression_adjusted_points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['handheld_id'], ['handhelds.id'], ),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_number', 'handheld_id', 'closed_at_uptime_ms', name='uq_submission_idempotency')
    )
    op.create_index(op.f('ix_judging_submissions_car_id'), 'judging_submissions', ['car_id'], unique=False)
    op.create_index(op.f('ix_judging_submissions_entry_number'), 'judging_submissions', ['entry_number'], unique=False)
    op.create_index(op.f('ix_judging_submissions_handheld_id'), 'judging_submissions', ['handheld_id'], unique=False)
    op.create_index(op.f('ix_judging_submissions_show_id'), 'judging_submissions', ['show_id'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('entry_number', sa.String(length=10), nullable=False),
    sa.Column('photo_type', sa.Enum('CAR', 'JUDGE_SHEET', name='phototype', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('MATCHED', 'DUPLICATE', 'UNMATCHED', name='photostatus', native_enum=False, length=16), nullable=False),
    sa.Column('source_handheld_id', sa.Integer(), nullable=True),
    sa.Column('transfer_method', sa.Enum('USB', 'WIFI', name='transfermethod', native_enum=False, length=16), nullable=False),
    sa.Column('transferred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ),
    sa.ForeignKeyConstraint(['source_handheld_id'], ['handhelds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_car_id'), 'photos', ['car_id'], unique=False)
    op.create_index(op.f('ix_photos_entry_number'), 'photos', ['entry_number'], unique=False)
    op.create_index(op.f('ix_photos_show_id'), 'photos', ['show_id'], unique=False)
    op.create_index(op.f('ix_photos_source_handheld_id'), 'photos', ['source_handheld_id'], unique=False)
    op.create_table('vehicle_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make_name', sa.String(length=80), nullable=False),
    sa.Column('model_name', sa.String(length=80), nullable=False),
    sa.Column('normalized_key', sa.String(length=200), nullable=False),
    sa.Column('times_seen', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'IGNORED', 'MERGED', name='vehiclecandidatestatus', native_enum=False, length=16), nullable=False),
    sa.Column('merged_into_model_id', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merged_into_model_id'], ['vehicle_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_candidates_normalized_key'), 'vehicle_candidates', ['normalized_key'], unique=True)
    op.create_table('award_nominations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('award_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['award_id'], ['awards.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['judging_submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'award_id', name='uq_nomination_submission_award')
    )
    op.create_index(op.f('ix_award_nominations_award_id'), 'award_nominations', ['award_id'], unique=False)
    op.create_index(op.f('ix_award_nominations_submission_id'), 'award_nominations', ['submission_id'], unique=False)
    op.create_table('judging_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('original_points', sa.Integer(), nullable=False),
    sa.Column('original_range_max', sa.Integer(), nullable=False),
    sa.Column('adjusted_points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['judging_categories.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['judging_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_judging_scores_category_id'), 'judging_scores', ['category_id'], unique=False)
    op.create_index(op.f('ix_judging_scores_submission_id'), 'judging_scores', ['submission_id'], unique=False)
    op.create_table('vehicle_candidate_sightings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['vehicle_candidates.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_candidate_sightings_candidate_id'), 'vehicle_candidate_sightings', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_vehicle_candidate_sightings_entry_id'), 'vehicle_candidate_sightings', ['entry_id'], unique=False)
    op.create_index(op.f('ix_vehicle_candidate_sightings_show_id'), 'vehicle_candidate_sightings', ['show_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_candidate_sightings_show_id'), table_name='vehicle_candidate_sightings')
    op.drop_index(op.f('ix_vehicle_candidate_sightings_entry_id'), table_name='vehicle_candidate_sightings')
    op.drop_index(op.f('ix_vehicle_candidate_sightings_candidate_id'), table_name='vehicle_candidate_sightings')
    op.drop_table('vehicle_candidate_sightings')
    op.drop_index(op.f('ix_judging_scores_submission_id'), table_name='judging_scores')
    op.drop_index(op.f('ix_judging_scores_category_id'), table_name='judging_scores')
    op.drop_table('judging_scores')
    op.drop_index(op.f('ix_award_nominations_submission_id'), table_name='award_nominations')
    op.drop_index(op.f('ix_award_nominations_award_id'), table_name='award_nominations')
    op.drop_table('award_nominations')
    op.drop_index(op.f('ix_vehicle_candidates_normalized_key'), table_name='vehicle_candidates')
    op.drop_table('vehicle_candidates')
    op.drop_index(op.f('ix_photos_source_handheld_id'), table_name='photos')
    op.drop_index(op.f('ix_photos_show_id'), table_name='photos')
    op.drop_index(op.f('ix_photos_entry_number'), table_name='photos')
    op.drop_index(op.f('ix_photos_car_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_judging_submissions_show_id'), table_name='judging_submissions')
    op.drop_index(op.f('ix_judging_submissions_handheld_id'), table_name='judging_submissions')
    op.drop_index(op.f('ix_judging_submissions_entry_number'), table_name='judging_submissions')
    op.drop_index(op.f('ix_judging_submissions_car_id'), table_name='judging_submissions')
    op.drop_table('judging_submissions')
    op.drop_index(op.f('ix_awards_show_id'), table_name='awards')
    op.drop_table('awards')
    op.drop_index(op.f('ix_vehicle_models_make_id'), table_name='vehicle_models')
    op.drop_table('vehicle_models')
    op.drop_index(op.f('ix_judging_categories_show_id'), table_name='judging_categories')
    op.drop_table('judging_categories')
    op.drop_index(op.f('ix_cars_show_id'), table_name='cars')
    op.drop_index(op.f('ix_cars_entry_number'), table_name='cars')
    op.drop_table('cars')
    op.drop_table('app_settings')
    op.drop_table('vehicle_makes')
    op.drop_table('shows')
    op.drop_table('handhelds')
    # ### end Alembic commands ###
