"""add app_settings table

Revision ID: d96c4ade65f2
Revises: 5e0a76389d5b
Create Date: 2026-08-29 20:14:35.108595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd96c4ade65f2'
down_revision: Union[str, Sequence[str], None] = '5e0a76389d5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active_show_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['active_show_id'], ['shows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_settings')
    # ### end Alembic commands ###
