"""add awards table and submission note

Revision ID: fe59e5f43afd
Revises: a494c9a6ec9d
Create Date: 2026-08-29 21:11:00.144731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe59e5f43afd'
down_revision: Union[str, Sequence[str], None] = 'a494c9a6ec9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('awards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.Enum('OVERALL', 'CRITERIA', 'CLASS', name='awardcategory', native_enum=False, length=16), nullable=False),
    sa.Column('criteria_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('winner_car_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['car_classes.id'], ),
    sa.ForeignKeyConstraint(['criteria_id'], ['judging_criteria.id'], ),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ),
    sa.ForeignKeyConstraint(['winner_car_id'], ['cars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_awards_show_id'), 'awards', ['show_id'], unique=False)
    op.add_column('judging_submissions', sa.Column('note', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('judging_submissions', 'note')
    op.drop_index(op.f('ix_awards_show_id'), table_name='awards')
    op.drop_table('awards')
    # ### end Alembic commands ###
