"""Exports firmware's real vehicle seed source (vehicle_seed_source.json —
NHTSA vPIC + curated-classic, provenance-documented, the SAME data the
physical handheld's build_vehicle_seed.py compiles into flash) as a flat
JSON array the browser simulator's vehicle_selector.js consumes directly.

Why this exists (see DECISIONS.md's SIM1 entry): the task that asked for
this originally described "the simulator form of the master vehicle data
generated by HB5's preparation script" — but HB5 (Home Base's vehicle
candidate-review/approval workflow) doesn't exist yet: no preparation
script, no export, no populated VehicleMake/VehicleModel rows anywhere.
Rather than invent a SECOND vehicle list for the simulator or block on
building HB5 for real, this script exports the ALREADY-real,
already-sourced firmware seed data instead — one master list, never a
duplicate. Full HB5 (the review queue, learned-vocabulary approval)
stays out of scope here.

Output shape: [{"make": "...", "models": ["...", ...]}, ...] — sorted,
provenance/source tags dropped (the simulator doesn't need them; they're
preserved in vehicle_seed_source.json itself for anyone who does).

Run this from the repo root: python firmware/tools/export_vehicle_data_for_simulator.py
Re-run whenever vehicle_seed_source.json changes (e.g. after
merge_seed_source.py regenerates it) — this script's output is generated,
not hand-maintained, and should never be edited directly.
"""
import json
import os


def main():
    src_path = "firmware/tools/vehicle_seed_source.json"
    out_path = "homebase/app/static/simulator/data/vehicle_data.json"

    with open(src_path, encoding="utf-8") as f:
        src = json.load(f)

    out = [
        {
            "make": entry["make"],
            "models": sorted(model["name"] for model in entry["models"]),
        }
        for entry in sorted(src["makes"], key=lambda e: e["make"].lower())
    ]

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(out, f, indent=1)

    total_models = sum(len(m["models"]) for m in out)
    print(f"Exported {len(out)} makes, {total_models} models -> {out_path}")


if __name__ == "__main__":
    main()
